### ISSUE TITLE
Should os.makedirs before reading/writing

### ISSUE THREAD

**Issue by notpushkin** [RiskIQ/pyyamlcfg#1]
I'm getting this kind of error:

``` python-traceback
Traceback (most recent call last):
  File "/home/ale/dev/rocket-api/rock-cli/venv/bin/rock", line 9, in <module>
    load_entry_point('rock-cli==0.1', 'console_scripts', 'rock')()
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ale/dev/rocket-api/rock-cli/rock_cli/cli.py", line 30, in register
    ctx.obj['config'].write()
  File "/home/ale/dev/rocket-api/rock-cli/venv/lib/python3.4/site-packages/yamlcfg/yml.py", line 107, in write
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ale/.config/rock-cli/config.yml'
```

I think that's because the `/home/ale/.config/rock-cli/` directory doesn't exist. It would've been great if some mkdirp stuff was done before trying to read or write the config.

**Comment by johannestaas** [comment]
Got it! I'll get that fixed in the next patch release.

**Comment by johannestaas** [comment]
Release 0.5.3, should be patched

yaml_config.write will now return the absolute path to the config it created, and create the directories if they don't exist.

**Comment by notpushkin** [comment]
Sweet, thanks!
